apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
spec:
  selector:
    app: "{{ .Values.deployment.metadata.labels.app }}"
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8080
      nodePort: 30001
